#!/bin/bash

# install jupyterlab extensions
jupyter labextension install --no-build @jupyterlab/server-proxy
jupyter labextension install --no-build @pyviz/jupyterlab_pyviz

# enable server extensions
jupyter serverextension enable jupyterlab_sql --py --sys-prefix
jupyter lab build

# install vscode extensions
code-server --install-extension ms-python.python
